version = "1.1.7"

[class]
remote-viewer = ""
songrec = ""
"(?i)alacritty" = ""
scli = ""
qalculate-gtk = ""
wayvnc = "󰀄"
dmenu-browser = ""
"dmenu-pass generator" = ""
kicad = ""
"(?i)waydroid.*" = "droid"
steam = ""
cssh = ""
calibre-gui = ""
"(?i)firefox" = "<span color='orange'> </span>"
dmenu-clipboard = ""
nm-connection-editor = ""
whatsapp-nativefier-d52542 = ""
neomutt = ""
taskwarrior-tui = ""
chromium = ""
telegramdesktop = ""
dmenu-emoji = ""
org-qutebrowser-qutebrowser = ""
gsimplecalc = ""
org-pwmt-zathura = ""
sun-awt-x11-xframepeer = ""
molotov = ""
shopping = ""
DEFAULT = ""
jetbrains-studio = ""
vncviewer = ""
libreoffice-startcenter = ""
org-telegram-desktop = ""
obsidian = ""
burp-startburp = ""
"(?i)kitty" = ""
qutepreview = ""
swappy = ""
sandboxed-tor-browser = ""
spotify = ""
whatsapp-desktop = ""
snappergui = ""
zoom = ""
code-oss = ""
krita = ""
kak = ""
duolingo = ""
libreoffice-impress = ""
element = ""
libreoffice-calc = ""
mpv = ""
plexamp = ""
slack = ""
udiskie = ""
pavucontrol = ""
vimiv = ""
darktable = ""
org-ksnip-ksnip = ""
gcr-prompter = ""
virt-manager = ""
vlc = ""
work = ""
fontforge = ""
Signal = ""
wlfreerdp = "󰀄"
nemo = ""
xplr = ""
wireshark-gtk = ""
streamlink-twitch-gui = ""
libreoffice-writer = ""
discord = ""
"Gimp-2.10" = ""
personal = ""
paperwork = ""
dmenu-pass = ""
bleachbit = ""
wire = "󰁀"
rapid-photo-downloader = ""
".*transmission.*" = ""
chrome-faolnafnngnfdaknnbpnkhgohbobgegn-default = ""

[class_active]
DEFAULT = "{icon}"
"(?i)firefox" = "<span color='orange'> {class}</span>"

[initial_class]

[initial_class_active]

[workspaces_name]
10 = "ten"
2 = "two"
6 = "six"
3 = "three"
0 = "zero"
8 = "eight"
1 = "one"
5 = "five"
4 = "four"
7 = "seven"
9 = "nine"

[title_in_class."(?i)foot"]
"emerge: (.+?/.+?)-.*" = "{match1}"

[title_in_class."(firefox|chrom.*)"]
"(?i)twitch" = "ꟳ"
"(?i)youtube" = "ꟳ"

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class.kitty]
zsh = ""

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"" = "^$"

[format]
dedup = false
dedup_inactive_fullscreen = false
delim = " "
workspace = "{clients}   "
client = "{icon}"
client_fullscreen = "[{icon}]"
client_dup = "{icon}{counter_sup}"
client_dup_fullscreen = "[{icon}]{counter_sup}"
