pragma Singleton

import Quickshell
import Quickshell.Io
import QtQuick

// News service
// Consumes the atomically published rss.py cache. FileView/watchChanges is the
// freshness path; the fallback timer only repairs missed filesystem events.
// The /tmp path remains a compatibility fallback for pre-schema caches.
QtObject {
    id: root

    // Cache generated by rss-news-cache.service; script is only used for click-through details.
    property string scriptPath: String("/home/zarred/scripts/rss/rss.py")
    property string cachePath: String(Quickshell.env("RSS_NEWS_CACHE_PATH") || "/tmp/rss-news")
    readonly property string persistentCachePath: resolvePersistentCachePath()
    property string category: "news"

    // intervalMs is retained for callers that configured the old poller. Cache
    // publication is now event-driven, with only a five-minute repair reload.
    property int intervalMs: 1800 * 1000
    property int devFirstIntervalMs: 60 * 1000
    property int fallbackIntervalMs: 5 * 60 * 1000
    property int staleAfterMs: 15 * 60 * 1000
    property int minManualIntervalMs: 10 * 1000
    property int manualRefreshTimeoutMs: 6 * 60 * 1000

    // State retained for existing consumers plus the versioned cache metadata.
    property bool checking: false
    property bool ready: false
    property bool stale: false
    property string status: "loading"
    property date lastUpdated: new Date(0)
    property date lastSuccessAt: new Date(0)
    property string error: ""
    property string cacheError: ""
    property string serviceError: ""
    property string cacheGeneration: ""
    property int cacheSchemaVersion: 0
    property string cacheStatus: ""
    property string refreshStatus: ""
    property string cacheCreatedAt: ""
    property string cacheUpdatedAt: ""
    property string cacheSourceInputHash: ""
    property int cacheAgeSeconds: -1
    property bool cacheAgeKnown: false
    property string cacheAgeText: "unknown"
    property string cacheSource: ""

    property string _persistentReadError: ""
    property string _legacyReadError: ""

    // Short aliases make the versioned contract convenient for newer consumers
    // while retaining the explicit cache-prefixed properties above.
    readonly property string generation: cacheGeneration
    readonly property int schemaVersion: cacheSchemaVersion
    readonly property string createdAt: cacheCreatedAt
    readonly property string updatedAt: cacheUpdatedAt
    readonly property string sourceInputHash: cacheSourceInputHash

    property string summaryText: "…"
    property string tooltipText: "(loading)"

    // Structured entries from JSON output
    property var entries: []
    property int entryCount: 0

    // Entry detail view state
    property string selectedEntryId: ""
    property var selectedEntryData: null
    property bool fetchingDetails: false

    // Buffer for entry details fetch
    property string _entryDetailsBuffer: ""
    property string _detailError: ""
    property Process _entryDetailsProcess: Process {
        running: false
        stdout: SplitParser {
            onRead: function(data) { root._entryDetailsBuffer += data.toString() }
        }
        onExited: function(code) {
            root.fetchingDetails = false
            if (code === 0) {
                try {
                    var data = JSON.parse(root._entryDetailsBuffer.trim())
                    var entry = Array.isArray(data) ? data[0] : data
                    // Process entry data to normalize fields
                    root.selectedEntryData = root._processEntryData(entry)
                    root._detailError = ""
                } catch(e) {
                    root.selectedEntryData = null
                    root._detailError = "Failed to parse entry details"
                }
            } else {
                root._detailError = "Error loading entry details (code: " + code + ")"
            }
            root._updateAggregateStatus()
            // Process is reused, don't destroy it
        }
    }

    // Reference counting keeps file watching and the repair timers inactive when unused.
    property int refCount: 0
    property double _lastManualMs: 0
    property double _cacheTimestampMs: 0
    property bool _persistentCacheValid: false
    property bool _manualWaiting: false
    property string _manualPreviousGeneration: ""
    property double _manualStartedAtMs: 0
    property double _manualGraceUntilMs: 0
    property string _serviceStatusSummary: ""
    property string _serviceStatusError: ""

    property FileView cacheFile: FileView {
        path: root.persistentCachePath
        preload: root.refCount > 0
        watchChanges: root.refCount > 0
        printErrors: false

        onLoaded: root._handleSummaryOutput(text(), "persistent")
        onLoadFailed: root._handleCacheReadFailure("Persistent news cache could not be read", "persistent")
        onFileChanged: root.cacheReloadTimer.restart()
    }

    // Compatibility with the pre-schema /tmp cache while the persistent cache is
    // created for the first time or during a state-directory migration.
    property FileView legacyCacheFile: FileView {
        path: root.cachePath
        preload: root.refCount > 0
        watchChanges: root.refCount > 0
        printErrors: false

        onLoaded: root._handleSummaryOutput(text(), "legacy")
        onLoadFailed: root._handleCacheReadFailure("News cache could not be read", "legacy")
        onFileChanged: root.cacheReloadTimer.restart()
    }

    property Timer cacheReloadTimer: Timer {
        interval: 100
        repeat: false
        onTriggered: root._reloadCacheFiles()
    }

    // This is deliberately a repair reload, not the primary freshness mechanism.
    property Timer fallbackTimer: Timer {
        interval: root.fallbackIntervalMs
        repeat: true
        running: root.refCount > 0
        onTriggered: root._reloadCacheFiles()
    }

    property Timer stalenessTimer: Timer {
        interval: 60 * 1000
        repeat: true
        running: root.refCount > 0
        onTriggered: root._updateAggregateStatus()
    }

    property Timer manualTimeoutTimer: Timer {
        interval: root.manualRefreshTimeoutMs
        repeat: false
        onTriggered: root._finishManualFailure(
            "Timed out waiting for a newer successful news cache generation"
            + (root._serviceStatusSummary ? " (" + root._serviceStatusSummary + ")" : ""))
    }

    property Timer serviceStatusTimer: Timer {
        interval: 2 * 1000
        repeat: true
        running: root._manualWaiting
        onTriggered: root._checkRefreshService()
    }

    property string _manualStartStderr: ""
    property Process manualStartProcess: Process {
        running: false
        stdout: SplitParser { onRead: function(_) {} }
        stderr: SplitParser {
            onRead: function(data) { root._manualStartStderr += data.toString() }
        }
        onExited: function(code) { root._handleManualStartExit(code) }
    }

    property string _serviceStatusOutput: ""
    property Process serviceStatusProcess: Process {
        running: false
        stdout: SplitParser {
            onRead: function(data) { root._serviceStatusOutput += data.toString() }
        }
        stderr: SplitParser { onRead: function(_) {} }
        onExited: function(code) { root._handleRefreshServiceStatus(code) }
    }

    onRefCountChanged: {
        if (refCount > 0)
            refresh(false)
    }

    function resolvePersistentCachePath() {
        var explicit = String(Quickshell.env("RSS_NEWS_LAST_GOOD_PATH") || "").trim()
        if (explicit !== "")
            return explicit

        var stateDir = String(Quickshell.env("XDG_STATE_HOME") || "").trim()
        if (stateDir === "") {
            var home = String(Quickshell.env("HOME") || "").trim()
            stateDir = home !== "" ? home + "/.local/state" : "/tmp"
        }
        return stateDir + "/rss-news/rss-news.json"
    }

    function canManual() {
        return (Date.now() - _lastManualMs) >= minManualIntervalMs
    }

    function refresh(manual) {
        var isManual = manual === true
        if (checking)
            return
        if (isManual && !canManual())
            return

        checking = true
        serviceError = ""
        _detailError = ""

        if (!isManual) {
            _updateAggregateStatus()
            _reloadCacheFiles()
            return
        }

        _lastManualMs = Date.now()
        _manualPreviousGeneration = cacheGeneration
        _manualStartedAtMs = Date.now()
        _manualWaiting = true
        _manualGraceUntilMs = Date.now() + 2000
        _serviceStatusSummary = "starting"
        _serviceStatusError = ""
        _manualStartStderr = ""
        manualTimeoutTimer.restart()
        _updateAggregateStatus()

        // --no-block is intentional: an already-active oneshot must not turn
        // systemctl's successful request into a false refresh completion.
        manualStartProcess.command = ["systemctl", "--user", "--no-block", "start", "rss-news-cache.service"]
        manualStartProcess.running = true
    }

    function _reloadCacheFiles() {
        if (refCount <= 0)
            return
        cacheFile.reload()
        legacyCacheFile.reload()
    }

    function _updateCacheError() {
        var messages = []
        if (_persistentReadError)
            messages.push(_persistentReadError)
        if (_legacyReadError)
            messages.push(_legacyReadError)
        cacheError = messages.join("; ")
    }

    function _handleCacheReadFailure(message, source) {
        if (source === "legacy" && _persistentCacheValid)
            return
        if (source === "persistent")
            _persistentReadError = message
        else
            _legacyReadError = message
        _updateCacheError()
        if (!_manualWaiting)
            checking = false
        _updateAggregateStatus()
    }

    function _parseCache(output) {
        var trimmed = String(output || "").trim()
        if (!trimmed)
            throw "news cache is empty"

        var data
        try {
            data = JSON.parse(trimmed)
        } catch (e) {
            throw "news cache JSON could not be parsed"
        }
        if (!data || typeof data !== "object" || Array.isArray(data))
            throw "news cache JSON is not an object"

        var schemaVersion = data.schema_version === undefined ? 0 : Number(data.schema_version)
        if (!isFinite(schemaVersion) || schemaVersion < 0 || schemaVersion > 2)
            throw "unsupported news cache schema version"

        var refreshStatus = String(data.refresh_status || "success").toLowerCase()
        if (refreshStatus !== "success")
            throw "news cache reports refresh status " + refreshStatus

        if (data.text !== undefined && data.text !== null && typeof data.text !== "string")
            throw "news cache has invalid summary text"
        if (data.entries !== undefined && !Array.isArray(data.entries))
            throw "news cache has invalid entries"
        return data
    }

    function _timestampMs(value) {
        if (value === undefined || value === null || value === "")
            return 0
        var parsed = Date.parse(String(value))
        return isFinite(parsed) ? parsed : 0
    }

    function _isNewGeneration(candidate, candidateTimestampMs) {
        if (candidate === "" || candidate === _manualPreviousGeneration)
            return false
        // A manual refresh can start before the first FileView load. In that
        // case any old schema-2 cache is not proof that the service completed.
        return candidateTimestampMs > 0 && candidateTimestampMs >= _manualStartedAtMs
    }

    function _handleSummaryOutput(output, source) {
        if (source === "legacy" && _persistentCacheValid)
            return

        var data
        try {
            data = _parseCache(output)
        } catch (e) {
            _handleCacheReadFailure(String(e), source)
            return
        }

        var generation = String(data.generation || "")
        var updatedAt = String(data.updated_at || "")
        var createdAt = String(data.created_at || "")
        var timestampMs = _timestampMs(updatedAt) || _timestampMs(createdAt)
        // FileView callbacks can arrive out of order around atomic replacement
        // or a repair reload. Never let an older persistent/legacy callback
        // roll the visible cache back; persistent wins an equal-timestamp tie.
        if (_cacheTimestampMs > 0 && (
                timestampMs <= 0 || timestampMs < _cacheTimestampMs ||
                (timestampMs === _cacheTimestampMs && cacheSource === "persistent" && source === "legacy")))
            return

        var previousGeneration = cacheGeneration
        var manualGenerationObserved = _manualWaiting
            && _isNewGeneration(generation, timestampMs)

        if (data.text !== undefined && data.text !== null)
            summaryText = String(data.text)
        if (data.tooltip !== undefined && data.tooltip !== null)
            tooltipText = String(data.tooltip)
        if (Array.isArray(data.entries)) {
            entries = data.entries
            entryCount = data.entries.length
        }

        cacheGeneration = generation
        cacheSchemaVersion = data.schema_version === undefined ? 0 : Number(data.schema_version)
        cacheStatus = String(data.refresh_status || "success")
        refreshStatus = cacheStatus
        cacheCreatedAt = createdAt
        cacheUpdatedAt = updatedAt
        cacheSourceInputHash = String(data.source_input_hash || "")
        cacheSource = source
        _cacheTimestampMs = timestampMs
        cacheAgeSeconds = timestampMs > 0
            ? Math.max(0, Math.floor((Date.now() - timestampMs) / 1000))
            : -1
        cacheAgeKnown = cacheAgeSeconds >= 0
        lastUpdated = timestampMs > 0 ? new Date(timestampMs) : new Date()
        lastSuccessAt = new Date()
        ready = true
        if (source === "persistent") {
            _persistentCacheValid = true
            _persistentReadError = ""
            _legacyReadError = ""
        } else {
            _legacyReadError = ""
        }
        _updateCacheError()

        if (manualGenerationObserved)
            _finishManualSuccess()
        else if (!_manualWaiting)
            checking = false
        _updateAggregateStatus()

        if (previousGeneration !== generation && generation !== "")
            console.log("News: loaded cache generation " + generation)
    }

    function _formatAge(seconds) {
        if (seconds < 0)
            return "unknown age"
        if (seconds < 60)
            return "less than 1m old"
        var minutes = Math.floor(seconds / 60)
        if (minutes < 60)
            return minutes + "m old"
        var hours = Math.floor(minutes / 60)
        if (hours < 24)
            return hours + "h " + (minutes % 60) + "m old"
        return Math.floor(hours / 24) + "d old"
    }

    function _updateAggregateStatus() {
        if (ready) {
            cacheAgeSeconds = _cacheTimestampMs > 0
                ? Math.max(0, Math.floor((Date.now() - _cacheTimestampMs) / 1000))
                : -1
            cacheAgeKnown = cacheAgeSeconds >= 0
            cacheAgeText = _formatAge(cacheAgeSeconds)
            stale = cacheAgeKnown && cacheAgeSeconds * 1000 > staleAfterMs
        } else {
            cacheAgeSeconds = -1
            cacheAgeKnown = false
            cacheAgeText = "unknown age"
            stale = false
        }

        var messages = []
        if (cacheError)
            messages.push(cacheError)
        if (serviceError)
            messages.push(serviceError)
        if (ready && stale)
            messages.push("News cache is stale (" + cacheAgeText + ")")
        else if (ready && !cacheAgeKnown)
            messages.push("News cache age unavailable")
        if (_detailError)
            messages.push(_detailError)
        error = messages.join("; ")

        if (_manualWaiting) {
            status = _serviceStatusSummary === "starting" ? "starting" : "waiting"
        } else if (!ready) {
            status = cacheError ? "error" : "loading"
        } else if (stale) {
            status = "stale"
        } else if (cacheError || serviceError) {
            status = "error"
        } else if (cacheSchemaVersion === 0) {
            status = "legacy"
        } else {
            status = "ready"
        }
    }

    function _handleManualStartExit(code) {
        if (!_manualWaiting)
            return
        if (code !== 0) {
            var detail = _manualStartStderr.trim()
            _finishManualFailure("Could not start rss-news-cache.service"
                                 + (detail ? ": " + detail : " (exit code " + code + ")"))
            return
        }

        _serviceStatusSummary = "running"
        _updateAggregateStatus()
        _checkRefreshService()
    }

    function _checkRefreshService() {
        if (!_manualWaiting || serviceStatusProcess.running)
            return
        _serviceStatusOutput = ""
        serviceStatusProcess.command = [
            "systemctl", "--user", "show", "rss-news-cache.service",
            "--property=ActiveState", "--property=SubState",
            "--property=Result", "--property=ExecMainStatus"
        ]
        serviceStatusProcess.running = true
    }

    function _handleRefreshServiceStatus(code) {
        if (!_manualWaiting)
            return
        if (code !== 0) {
            _serviceStatusError = "Could not inspect rss-news-cache.service"
            if (Date.now() >= _manualGraceUntilMs)
                _finishManualFailure(_serviceStatusError)
            return
        }

        var fields = {}
        var lines = _serviceStatusOutput.trim().split("\n")
        for (var i = 0; i < lines.length; i++) {
            var separator = lines[i].indexOf("=")
            if (separator > 0)
                fields[lines[i].substring(0, separator)] = lines[i].substring(separator + 1).trim()
        }

        var active = fields.ActiveState || "unknown"
        var result = fields.Result || "unknown"
        var exitStatus = fields.ExecMainStatus || ""
        _serviceStatusSummary = "service " + active + "/" + (fields.SubState || "unknown")
                            + ", result " + result
        if (exitStatus !== "")
            _serviceStatusSummary += ", exit " + exitStatus
        _updateAggregateStatus()

        if (Date.now() < _manualGraceUntilMs)
            return
        var failedResult = ["failed", "dependency", "exit-code", "timeout", "signal", "watchdog", "resources", "start-limit-hit"].indexOf(result) >= 0
        // Result/ExecMainStatus can still describe the previous invocation
        // while a new --no-block start is activating. Only fail on a terminal
        // failed/inactive state, not merely a failed-looking result field.
        if (active === "failed" || (active === "inactive" && failedResult))
            _finishManualFailure("rss-news-cache.service failed (" + _serviceStatusSummary + ")")
    }

    function _finishManualSuccess() {
        _manualWaiting = false
        manualTimeoutTimer.stop()
        serviceError = ""
        checking = false
        _updateAggregateStatus()
    }

    function _finishManualFailure(message) {
        if (!_manualWaiting && !checking)
            return
        _manualWaiting = false
        manualTimeoutTimer.stop()
        checking = false
        serviceError = message
        _updateAggregateStatus()
    }

    function fetchEntryDetails(entryId) {
        if (fetchingDetails || !entryId) return
        fetchingDetails = true
        selectedEntryId = entryId
        selectedEntryData = null
        _detailError = ""
        _updateAggregateStatus()
        
        // Reset buffer and configure process
        _entryDetailsBuffer = ""
        _entryDetailsProcess.command = [scriptPath, '-i', entryId, '-s', '--json']
        _entryDetailsProcess.running = true
    }

    function clearSelectedEntry() {
        selectedEntryId = ""
        selectedEntryData = null
    }

    // Process entry data to normalize fields and strip HTML
    function _processEntryData(entry) {
        if (!entry) return null
        
        var processed = {}
        
        // Copy basic fields
        processed.id = entry.id || ""
        processed.title = entry.title || "No title"
        processed.author = entry.author || ""
        processed.categories = entry.categories || []
        
        // Handle feed name - from origin.title or _feed_title
        processed.feed = entry._feed_title || (entry.origin ? entry.origin.title : "") || ""
        
        // Handle date - convert from timestamp
        if (entry.published) {
            var date = new Date(entry.published * 1000)
            processed.date = date.toLocaleDateString()
        } else {
            processed.date = ""
        }
        
        // Handle summary - might be dict with content or string
        if (entry.summary && typeof entry.summary === 'object' && entry.summary.content) {
            processed.summary = root._stripHtml(entry.summary.content)
        } else if (typeof entry.summary === 'string') {
            processed.summary = root._stripHtml(entry.summary)
        } else {
            processed.summary = ""
        }
        
        // Handle content - might be dict with content or string
        if (entry.content && typeof entry.content === 'object' && entry.content.content) {
            processed.content = root._stripHtml(entry.content.content)
        } else if (typeof entry.content === 'string') {
            processed.content = root._stripHtml(entry.content)
        } else {
            processed.content = ""
        }
        
        // Get URL from canonical or alternate
        if (entry.canonical && entry.canonical.length > 0 && entry.canonical[0].href) {
            processed.url = entry.canonical[0].href
        } else if (entry.alternate && entry.alternate.length > 0 && entry.alternate[0].href) {
            processed.url = entry.alternate[0].href
        } else {
            processed.url = ""
        }
        
        return processed
    }

    // Strip HTML tags from text
    function _stripHtml(html) {
        if (!html || typeof html !== 'string') return ""
        // Replace common HTML entities
        var text = html.replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&')
                       .replace(/&quot;/g, '"').replace(/&#39;/g, "'")
        // Remove HTML tags
        text = text.replace(/<[^>]+>/g, ' ')
        // Normalize whitespace
        text = text.replace(/\s+/g, ' ').trim()
        return text
    }
}
