{ ... }: {
  wayland.windowManager.hyprland.settings = {
    windowrule = [
      #"tile, ^(Vtk)$"
      "workspace special, (special)$"
    ];
    windowrulev2 = [
      "float, class:^(nova|zoom|cctv|xdg-desktop-portal-gtk|steam)$"
      "float, initialTitle:^(Picture-in-Picture)$"
      "move 100%-w-10 40, initialTitle:^(Picture-in-Picture)$"
      "size 850 480, initialTitle:^(Picture-in-Picture)$"
      "pin, initialTitle:^(Picture-in-Picture)$"
      "noblur, initialTitle:^(Picture-in-Picture)$"
      "group barred, initialTitle:^(Picture-in-Picture)$"
      "opacity 1.0 override 0.7 override 1.0 override, initialTitle:^(Picture-in-Picture)$"
      "noinitialfocus, initialTitle:^(Picture-in-Picture)$"
      "size 800 500, class:^(nova)$"
      #"center, class:^(nova)$"
      #"pin, class:^(nova)$"
      #"stayfocused, class:^(nova)$"
      #"animation slidefadevert, class:^(waybar|nova)$"
      "rounding 6, class:^(waybar)$"
      "center, class:^(xdg-desktop-portal-gtk|zenity)$"
      "stayfocused, class:^(Pinentry)$"
      #"keepaspectratio, class:^(mpv)$"
      "noblur, class:^(mpv)$,floating:1,fullscreen:0"
      "suppressevent maximize, class:^(firefox)$"
      "suppressevent activatefocus, class:^(OrcaSlicer)$"
      "pin, title:^(ripdrag)$"
      "size 60% 50%, title:^(Enter name of file to save to…)$|class:xdg-desktop-portal-gtk"
      "float, title:^(mpd_cover)$"
      "size 1000 1000, title:^(mpd_cover)$"
      "pseudo, class:^(imv)$"
      "tile, class:^(kdeconnect.sms)$"
      "fullscreenstate -1 2, onworkspace:special:browser-tradingview"
      "fullscreenstate -1 2, onworkspace:special:browser-chatgpt"
      "fullscreenstate -1 2, onworkspace:special:browser-messages"
      "fullscreenstate -1 2, onworkspace:special:server"
    ];
    layerrule = [
      "blur, notifications"
      "blur, swaync-control-center"
      "blur, swaync-notification-window"
      "blur, waybar"
      "blur, rofi"
      "animation slidefadevert, rofi"
      "blur, wlroots"
      "blur, gtk-layer-shell"
      "blur, anyrun"
      "ignorezero, swaync-control-center"
      "ignorezero, notifications"
      "ignorezero, swaync-notification-window"
      "ignorezero, waybar"
      "ignorealpha 0.1, rofi"
      "ignorezero, wlroots"
      "ignorezero, gtk-layer-shell"
      "ignorezero, anyrun"
    ];
    workspace = [
      "1, monitor:DP-3, default:true"
      "5, monitor:DP-2, default:true"
      "special:stats, on-created-empty:kitty --class stats zsh -c 'btop', gapsout:40, gapsin:40"
      "special:volume, on-created-empty:pavucontrol, gapsout:40, gapsin:40"
      "special:scratchpad, on-created-empty:kitty --class kitty-scratchpad zsh -c 'tmux new -A -s scratchpad', gapsout:40, gapsin:40"
      "special:mail, on-created-empty:~/scripts/hyprland/special_mail.sh, gapsout:40, gapsin:40"
      "special:media, on-created-empty:~/scripts/hyprland/special_media.sh, gapsout:40, gapsin:40"
      #"special:music, on-created-empty:spotify & kitty zsh -c 'cava', gapsout:80, gapsin:80"
      "special:music, on-created-empty:spotify, gapsout:80, gapsin:80"
      "special:finance, on-created-empty:~/scripts/hyprland/special_finance.sh, gapsout:40, gapsin:40"
      "special:server, on-created-empty:~/scripts/hyprland/special_server.sh, gapsout:40, gapsin:40"
      "special:browser-tradingview, on-created-empty:firefox --new-window 'https://www.tradingview.com/chart', gapsout:40"
      "special:browser-chatgpt, on-created-empty:firefox --new-window 'https://chatgpt.com', gapsout:100"
      "special:browser-messages, on-created-empty:firefox --new-window 'https://messages.google.com/web', gapsout:40"
    ];
  };
}
