{ ... }: {
  wayland.windowManager.hyprland.settings = {
    windowrule = [
      "match:class ^(nova|zoom|xdg-desktop-portal-gtk|steam|org.kde.kdeconnect.daemon)$, float"
      #"match:tag pin, float"
      #"match:tag pin, move 100%-w-10 40"
      #"match:tag pin, size 850 480"
      #"match:tag pin, pin"
      #"match:tag pin, noblur"
      #"match:tag pin, group barred"
      #"match:tag pin, opacity 1.0 override 0.7 override 1.0 override"
      #"match:tag pin, no_initial_focus"
      "match:initial_title Picture-in-Picture|cctv|Syncthing Tray, float"
      "match:title nova, float"
      "match:initial_title Picture-in-Picture|cctv, move 100%-w-10 40"
      "match:initial_title Picture-in-Picture, size 850 480"
      "match:initial_title cctv, size 530 400"
      "match:initial_title Picture-in-Picture|cctv, pin"
      "match:initial_title Picture-in-Picture|cctv, noblur"
      "match:initial_title Picture-in-Picture|cctv, group barred"
      "match:initial_title Picture-in-Picture|cctv, opacity 1.0 override 0.7 override 1.0 override"
      "match:initial_title Picture-in-Picture|cctv, no_initial_focus"
      "match:initial_title Picture-in-Picture|cctv, tag +pin"
      "match:class ^(nova)$, size 1200 800"
      "match:title nova, size 1200 800"
      "match:class ^(nova|obsidian)$, dimaround"
      "match:title nova, dimaround"
      #"match:class ^(nova)$, center"
      #"match:class ^(nova)$, pin"
      #"match:class ^(nova)$, stayfocused"
      #"match:class ^(waybar|nova)$, animation slidefadevert"
      "match:class ^(waybar)$, rounding 6"
      "match:class ^(xdg-desktop-portal-gtk|zenity|Rofi)$, center"
      "match:class ^(Pinentry)$, stayfocused"
      "match:title ^(Hyprland Polkit Agent)$, stayfocused"
      #"match:class ^(mpv)$, keepaspectratio"
      "match:class ^(mpv)$ match:float true match:fullscreen false, noblur"
      "match:class ^(firefox)$, suppressevent maximize"
      "match:class ^(OrcaSlicer)$, suppressevent activatefocus"
      "match:title ^(ripdrag)$, pin"
      "match:title ^(Enter name of file to save to…)$ match:class xdg-desktop-portal-gtk, size 60% 50%"
      "match:title ^(mpd_cover|float)$, float"
      "match:title ^(mpd_cover)$, size 1000 1000"
      "match:class swayimg.*, pseudo"
      "match:class swayimg.*, float"
      "match:class ^(kdeconnect.sms)$, tile"
      "match:workspace special:browser-tradingview, fullscreenstate -1 2"
      "match:workspace special:browser-chatgpt, fullscreenstate -1 2"
      "match:workspace special:browser-messages, fullscreenstate -1 2"
      "match:workspace special:server, fullscreenstate -1 2"
    ];
    layerrule = [
      "blur, match:namespace notifications"
      "blur, match:namespace waybar"
      "blur, match:namespace primary-bar"
      "blur, match:namespace ignis_bar_0"
      "blur, match:namespace ignis_bar_1"
      "blur, match:namespace ignis_bar_2"
      "blur, match:namespace ignis_bar_3"
      "blur, match:namespace rofi"
      "animation slidefadevert, match:namespace rofi"
      "blur, match:namespace wlroots"
      "blur, match:namespace gtk-layer-shell"
      "blur, match:namespace anyrun"
      "blur, match:namespace swaync-control-center"
      "blur, match:namespace swaync-notification-window"
    ];
    workspace = [
      "1, monitor:DP-3, default:true"
      "5, monitor:DP-2, default:true"
      "special:obsidian, on-created-empty:obsidian, gapsout:40, gapsin:40"
      "special:stats, on-created-empty:kitty --class stats zsh -c 'btop', gapsout:40, gapsin:40"
      "special:volume, on-created-empty:pavucontrol, gapsout:40, gapsin:40"
      "special:scratchpad, on-created-empty:kitty --class kitty-scratchpad zsh -c 'tmux new -A -s scratchpad', gapsout:40, gapsin:40"
      "special:mail, on-created-empty:~/scripts/hyprland/special_mail.sh, gapsout:40, gapsin:40"
      "special:media, on-created-empty:~/scripts/hyprland/special_media.sh, gapsout:40, gapsin:40"
      #"special:music, on-created-empty:spotify & kitty zsh -c 'cava', gapsout:80, gapsin:80"
      "special:music, on-created-empty:spotify, gapsout:80, gapsin:80"
      "special:finance, on-created-empty:~/scripts/hyprland/special_finance.sh, gapsout:40, gapsin:40"
      "special:server, on-created-empty:~/scripts/hyprland/special_server.sh, gapsout:40, gapsin:40"
      "special:cameras, on-created-empty:~/scripts/hyprland/cctv, gapsout:40"
      "special:browser-tradingview, on-created-empty:firefox --new-window 'https://www.tradingview.com/chart', gapsout:40"
      "special:browser-chatgpt, on-created-empty:firefox --new-window 'https://chatgpt.com', gapsout:20"
      "special:browser-messages, on-created-empty:firefox --new-window 'https://messages.google.com/web', gapsout:40"
    ];
  };
}
