pragma Singleton

import Quickshell
import Quickshell.Io
import QtQuick

// News service
// Wraps external rss.py script to obtain summarized news text and tooltip list.
// Script usage (original waybar): rss.py -c news -s  (category + summarize) every 1800s.
// Output JSON example written to stdout and /tmp/rss-news:
//   {"text":"Compressed headline sentence","tooltip":"Full list of 30 feed entries"}
// Exposes:
//  - summaryText (string) main condensed text (or fallback "…")
//  - tooltipText (string) full multi-line entries
//  - lastUpdated (date), checking (bool), error (string)
//  - intervalMs (default 1800s production, devShortIntervalMs for first run override)
// Behavior:
//  - Uses refCount like other battery services so polling only active with consumers.
//  - On error retains prior values and sets error message; summaryText prefixed with '!'
//  - Manual refresh (refresh(true)) honors minManualIntervalMs
QtObject {
    id: root

    // Cache generated by rss-news-cache.service; script is only used for click-through details.
    property string scriptPath: String("/home/zarred/scripts/rss/rss.py")
    property string cachePath: String("/tmp/rss-news")
    property string category: "news"

    // Intervals
    property int intervalMs: 1800 * 1000   // 30 minutes
    property int devFirstIntervalMs: 60 * 1000 // shorter first poll for dev; after first success revert to intervalMs
    property int minManualIntervalMs: 10 * 1000

    // State
    property bool checking: false
    property date lastUpdated: new Date(0)
    property string error: ""

    property string summaryText: "…"
    property string tooltipText: "(loading)"

    // Structured entries from JSON output
    property var entries: []
    property int entryCount: 0

    // Entry detail view state
    property string selectedEntryId: ""
    property var selectedEntryData: null
    property bool fetchingDetails: false
    
    // Buffer for entry details fetch
    property string _entryDetailsBuffer: ""
    property Process _entryDetailsProcess: Process {
        running: false
        stdout: SplitParser {
            onRead: function(data) { root._entryDetailsBuffer += data.toString() }
        }
        onExited: function(code) {
            root.fetchingDetails = false
            if (code === 0) {
                try {
                    var data = JSON.parse(root._entryDetailsBuffer.trim())
                    var entry = Array.isArray(data) ? data[0] : data
                    // Process entry data to normalize fields
                    root.selectedEntryData = root._processEntryData(entry)
                } catch(e) {
                    root.selectedEntryData = null
                    root.error = "Failed to parse entry details"
                }
            } else {
                root.error = "Error loading entry details (code: " + code + ")"
            }
            // Process is reused, don't destroy it
        }
    }

    // Reference counting for polling
    property int refCount: 0

    property bool _firstPollDone: false
    property double _lastManualMs: 0

    property Timer pollTimer: Timer {
        interval: root._firstPollDone ? root.intervalMs : root.devFirstIntervalMs
        repeat: true
        running: root.refCount > 0
        onTriggered: root.refresh(false)
    }

    onRefCountChanged: {
        pollTimer.running = (refCount > 0)
        if (refCount > 0) refresh(false)
    }

    function canManual() {
        return (Date.now() - _lastManualMs) >= minManualIntervalMs
    }

    // Temporary storage for refresh output
    property string _summaryOutput: ""

    function refresh(manual) {
        if (checking) return
        if (manual === true && !canManual()) return
        if (manual === true) _lastManualMs = Date.now()
        checking = true
        error = ""
        _summaryOutput = ""

        if (manual === true) {
            var refreshProc = Qt.createQmlObject('import Quickshell.Io; import QtQuick; Process {}', root)
            refreshProc.command = ['systemctl', '--user', 'start', 'rss-news-cache.service']
            refreshProc.onExited.connect(function(code) {
                refreshProc.destroy()
                root._readCache()
            })
            refreshProc.running = true
            return
        }

        root._readCache()
    }

    function _readCache() {
        _summaryOutput = ""
        var cacheProc = Qt.createQmlObject('import Quickshell.Io; import QtQuick; Process { stdout: SplitParser { onRead: function(data) { root._summaryOutput += data.toString() } } }', root)
        cacheProc.command = ['cat', cachePath]
        cacheProc.onExited.connect(function(code) {
            if (code === 0) {
                root._handleSummaryOutput(root._summaryOutput)
            } else {
                error = "News cache unavailable"
            }
            checking = false
            cacheProc.destroy()
        })
        cacheProc.running = true
    }

    function _handleSummaryOutput(output) {
        var trimmed = (output || "").trim()
        if (!trimmed) return
        try {
            var data = JSON.parse(trimmed)
            if (data.text) {
                summaryText = data.text
                tooltipText = data.tooltip || tooltipText
                if (Array.isArray(data.entries)) {
                    entries = data.entries
                    entryCount = data.entries.length
                }
                lastUpdated = data.updated_at ? new Date(data.updated_at) : new Date()
                _firstPollDone = true
                pollTimer.interval = intervalMs
            }
        } catch(e) {
            // Non-fatal parse error
            console.log("News: Failed to parse summary output")
        }
    }

    function _handleJsonOutput(output) {
        var trimmed = (output || "").trim()
        if (!trimmed) return
        try {
            var data = JSON.parse(trimmed)
            if (Array.isArray(data)) {
                // Array of entries from --json
                entries = data
                entryCount = data.length
            }
        } catch(e) {
            console.log("News: Failed to parse JSON entries")
        }
    }

    function fetchEntryDetails(entryId) {
        if (fetchingDetails || !entryId) return
        fetchingDetails = true
        selectedEntryId = entryId
        selectedEntryData = null
        error = ""
        
        // Reset buffer and configure process
        _entryDetailsBuffer = ""
        _entryDetailsProcess.command = [scriptPath, '-i', entryId, '-s', '--json']
        _entryDetailsProcess.running = true
    }

    function clearSelectedEntry() {
        selectedEntryId = ""
        selectedEntryData = null
    }

    // Process entry data to normalize fields and strip HTML
    function _processEntryData(entry) {
        if (!entry) return null
        
        var processed = {}
        
        // Copy basic fields
        processed.id = entry.id || ""
        processed.title = entry.title || "No title"
        processed.author = entry.author || ""
        processed.categories = entry.categories || []
        
        // Handle feed name - from origin.title or _feed_title
        processed.feed = entry._feed_title || (entry.origin ? entry.origin.title : "") || ""
        
        // Handle date - convert from timestamp
        if (entry.published) {
            var date = new Date(entry.published * 1000)
            processed.date = date.toLocaleDateString()
        } else {
            processed.date = ""
        }
        
        // Handle summary - might be dict with content or string
        if (entry.summary && typeof entry.summary === 'object' && entry.summary.content) {
            processed.summary = root._stripHtml(entry.summary.content)
        } else if (typeof entry.summary === 'string') {
            processed.summary = root._stripHtml(entry.summary)
        } else {
            processed.summary = ""
        }
        
        // Handle content - might be dict with content or string
        if (entry.content && typeof entry.content === 'object' && entry.content.content) {
            processed.content = root._stripHtml(entry.content.content)
        } else if (typeof entry.content === 'string') {
            processed.content = root._stripHtml(entry.content)
        } else {
            processed.content = ""
        }
        
        // Get URL from canonical or alternate
        if (entry.canonical && entry.canonical.length > 0 && entry.canonical[0].href) {
            processed.url = entry.canonical[0].href
        } else if (entry.alternate && entry.alternate.length > 0 && entry.alternate[0].href) {
            processed.url = entry.alternate[0].href
        } else {
            processed.url = ""
        }
        
        return processed
    }

    // Strip HTML tags from text
    function _stripHtml(html) {
        if (!html || typeof html !== 'string') return ""
        // Replace common HTML entities
        var text = html.replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&')
                       .replace(/&quot;/g, '"').replace(/&#39;/g, "'")
        // Remove HTML tags
        text = text.replace(/<[^>]+>/g, ' ')
        // Normalize whitespace
        text = text.replace(/\s+/g, ' ').trim()
        return text
    }
}
